'use client'
import {Inter} from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
import "./globals.css";
import Header from "./_commponents/Header";
import Footer from "./_commponents/Footer";
import {CartContext} from "./_context/CartContext";
import { useState } from "react";
import {BookingContext} from "./_context/BookingContext";
const inter = Inter({ subsets: ['latin'], weight: "700"});


//export const metadata = {
  //title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);
  const [BookingDist, BookingDistDetails] = useState({});

  return (
    <ClerkProvider>
      <CartContext.Provider value={{cart, setCart}}>
      <BookingContext.Provider value={{ BookingDist, BookingDistDetails }}>
    <html lang="en">
      <body
        className={inter.className}
      >
        <Header />
        {children}
        <Footer />
         
      </body>
    </html>
    </BookingContext.Provider>
    </CartContext.Provider>
    </ClerkProvider>
  );
}
